package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/noonyuu/nfc/back/graph"
	"github.com/noonyuu/nfc/back/graph/model"
	"github.com/noonyuu/nfc/back/internal/config"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	// uuidを生成
	uid, _ := uuid.NewRandom()
	// 生成したUUIDを文字列に変換
	uidString := uid.String()
	// 現在時刻を取得
	now := time.Now()
	// User構造体にUUIDと現在時刻をセット
	user := &model.User{
		ID:        uidString,
		FirstName: input.FirstName,
		LastName:  input.LastName,
		Email:     input.Email,
		CreatedAt: now,
		UpdatedAt: now,
	}

	query := `
		INSERT INTO users (id, first_name, last_name, email, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, ?)
	`

	_, err := r.DB.Exec(query, user.ID, input.FirstName, input.LastName, input.Email, user.CreatedAt, user.UpdatedAt)
	if err != nil {
		return nil, err
	}

	// 作成したユーザーを返す
	return user, nil
}

// UserByID is the resolver for the userById field.
func (r *queryResolver) UserByID(ctx context.Context, id string) (*model.User, error) {
	query := `
		SELECT id, first_name, last_name, email, created_at, updated_at
		FROM users
		WHERE id = ?
	`
	row := r.DB.QueryRow(query, id)
	var user model.User
	var createdAtBytes []byte
	var updatedAtBytes []byte
	err := row.Scan(&user.ID, &user.FirstName, &user.LastName, &user.Email, &createdAtBytes, &updatedAtBytes)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("user not found")
		}
		return nil, err
	}

	// カスタムフォーマットを使用して created_at と updated_at を解析
	createdAt, err := config.CustomFormat(createdAtBytes)
	if err != nil {
		return nil, fmt.Errorf("error parsing created_at: %w", err)
	}

	updatedAt, err := config.CustomFormat(updatedAtBytes)
	if err != nil {
		return nil, fmt.Errorf("error parsing updated_at: %w", err)
	}

	user.CreatedAt = createdAt
	user.UpdatedAt = updatedAt

	return &user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	query := `
		SELECT id, first_name, last_name, email, created_at, updated_at
		FROM users
	`
	rows, err := r.DB.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var users []*model.User

	for rows.Next() {
		var user model.User
		var createdAtBytes []byte
		var updatedAtBytes []byte
		err = rows.Scan(&user.ID, &user.FirstName, &user.LastName, &user.Email, &createdAtBytes, &updatedAtBytes)
		if err != nil {
			if err == sql.ErrNoRows {
				return nil, fmt.Errorf("user not found")
			}
			return nil, err
		}
		// カスタムフォーマットを使用して created_at と updated_at を解析
		createdAt, err := config.CustomFormat(createdAtBytes)
		if err != nil {
			return nil, fmt.Errorf("error parsing created_at: %w", err)
		}

		updatedAt, err := config.CustomFormat(updatedAtBytes)
		if err != nil {
			return nil, fmt.Errorf("error parsing updated_at: %w", err)
		}
		// ユーザーが見つかった場合、ユーザーを返す
		user.CreatedAt = createdAt
		user.UpdatedAt = updatedAt

		users = append(users, &user)
	}

	if er := rows.Err(); er != nil {
		return nil, er
	}

	return users, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *model.User) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *model.User) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
