services:
  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      # target: dev
      # target: release
    # working_dir: /work
    command: ["air"]
    # command: ["/usr/local/bin/nfc"]
    container_name: go_app
    volumes:
      - .:/work
    ports:
      - "8080:8080"
    environment:
      ENV: Development
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    depends_on:
      - db
      - redis
    networks:
      - redis_network

  db:
    image: mysql:8.0
    container_name: mysql
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-time-zone='+9:00'"
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql:/ddl
      - ./docker/mysql/init/all_migrations.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - redis_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    tty: true
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - redis_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8443:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../front/dist:/var/www
    depends_on:
      - app
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  db_data:
  redis_data:

networks:
  redis_network:
    driver: bridge
