services:
  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: go_app
    volumes:
      - .:/work
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ENV: Development
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    depends_on:
      - db
      - redis
      - minio
    networks:
      - redis_network

  image:
    build:
      context: ./storage
      dockerfile: Dockerfile
    container_name: image
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - AWS_S3_FORCE_PATH_STYLE=true
      - CHOKIDAR_USEPOLLING=true

    ports:
      - "3001:3001"
    working_dir: /work
    restart: always
    networks:
      - redis_network

  db:
    image: mysql:8.0
    container_name: mysql
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-time-zone='+9:00'"
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql:/ddl
      - ./docker/mysql/init/all_migrations.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - redis_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    tty: true
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - redis_network

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data
    networks:
      - redis_network
    mem_limit: 256m
    mem_reservation: 128m

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8443:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../front/dist:/var/www
    depends_on:
      - app
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - redis_network

volumes:
  db_data:
  redis_data:
  minio_data:

networks:
  redis_network:
    driver: bridge
