services:
  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      # target: dev
      # target: release
    # working_dir: /work
    command: ["air"]
    # command: ["/usr/local/bin/nfc"]
    container_name: go_app
    volumes:
      - .:/work
    ports:
      - "8080:8080"
    environment:
      ENV: Development
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    depends_on:
      - db
      - redis
      - minio
    networks:
      - redis_network

  image:
    image: node
    container_name: image
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    ports:
      - "3001:3001"
    volumes:
      - ./storage/:/work
      - ./storage/.aws:/root/.aws:ro
    working_dir: /work
    command: ["sh", "-c", "rm -rf node_modules && npm install && npm run dev-ts"]
    networks:
      - redis_network

  db:
    image: mysql:8.0
    container_name: mysql
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-time-zone='+9:00'"
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql:/ddl
      - ./docker/mysql/init/all_migrations.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - redis_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    tty: true
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - redis_network

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data
    networks:
      - redis_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8443:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../front/dist:/var/www
    depends_on:
      - app
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - redis_network

volumes:
  db_data:
  redis_data:
  minio_data:

networks:
  redis_network:
    driver: bridge
