FROM golang:1.24-alpine

WORKDIR /work

RUN apk add --no-cache \
        alpine-sdk \
        git \
    && go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
