/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as WorksCreateImport } from './routes/works/create'
import { Route as ProfileEditImport } from './routes/profile/edit'
import { Route as NfcEventIdWorkIdIndexImport } from './routes/nfc/$eventId/$workId/index'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorksCreateRoute = WorksCreateImport.update({
  id: '/works/create',
  path: '/works/create',
  getParentRoute: () => rootRoute,
} as any)

const ProfileEditRoute = ProfileEditImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRoute,
} as any)

const NfcEventIdWorkIdIndexRoute = NfcEventIdWorkIdIndexImport.update({
  id: '/nfc/$eventId/$workId/',
  path: '/nfc/$eventId/$workId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditImport
      parentRoute: typeof rootRoute
    }
    '/works/create': {
      id: '/works/create'
      path: '/works/create'
      fullPath: '/works/create'
      preLoaderRoute: typeof WorksCreateImport
      parentRoute: typeof rootRoute
    }
    '/nfc/$eventId/$workId/': {
      id: '/nfc/$eventId/$workId/'
      path: '/nfc/$eventId/$workId'
      fullPath: '/nfc/$eventId/$workId'
      preLoaderRoute: typeof NfcEventIdWorkIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile/edit': typeof ProfileEditRoute
  '/works/create': typeof WorksCreateRoute
  '/nfc/$eventId/$workId': typeof NfcEventIdWorkIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile/edit': typeof ProfileEditRoute
  '/works/create': typeof WorksCreateRoute
  '/nfc/$eventId/$workId': typeof NfcEventIdWorkIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile/edit': typeof ProfileEditRoute
  '/works/create': typeof WorksCreateRoute
  '/nfc/$eventId/$workId/': typeof NfcEventIdWorkIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/profile/edit'
    | '/works/create'
    | '/nfc/$eventId/$workId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/profile/edit'
    | '/works/create'
    | '/nfc/$eventId/$workId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/profile/edit'
    | '/works/create'
    | '/nfc/$eventId/$workId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProfileEditRoute: typeof ProfileEditRoute
  WorksCreateRoute: typeof WorksCreateRoute
  NfcEventIdWorkIdIndexRoute: typeof NfcEventIdWorkIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProfileEditRoute: ProfileEditRoute,
  WorksCreateRoute: WorksCreateRoute,
  NfcEventIdWorkIdIndexRoute: NfcEventIdWorkIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/login",
        "/register",
        "/profile/edit",
        "/works/create",
        "/nfc/$eventId/$workId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/profile/edit": {
      "filePath": "profile/edit.tsx"
    },
    "/works/create": {
      "filePath": "works/create.tsx"
    },
    "/nfc/$eventId/$workId/": {
      "filePath": "nfc/$eventId/$workId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
