// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewEvent struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	StartDate   string `json:"startDate"`
	EndDate     string `json:"endDate"`
	Location    string `json:"location"`
	CreatedBy   string `json:"createdBy"`
	UpdatedBy   string `json:"updatedBy"`
}

type NewProfile struct {
	UserID         string  `json:"userId"`
	AvatarURL      *string `json:"avatarUrl,omitempty"`
	NickName       string  `json:"nickName"`
	GraduationYear *int32  `json:"graduationYear,omitempty"`
	Affiliation    *string `json:"affiliation,omitempty"`
	Bio            *string `json:"bio,omitempty"`
}

type NewProfileSkill struct {
	ProfileID string `json:"profileId"`
	SkillID   string `json:"skillId"`
}

type NewSkill struct {
	Name     string `json:"name"`
	Category string `json:"category"`
}

type NewUser struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}

type NewWork struct {
	EventID     string  `json:"eventId"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}

type NewWorkEvent struct {
	WorkID  string `json:"workId"`
	EventID string `json:"eventId"`
}

type NewWorkProfile struct {
	WorkID    string `json:"workId"`
	ProfileID string `json:"profileId"`
}

type NewWorkSkill struct {
	WorkID  string `json:"workId"`
	SkillID string `json:"skillId"`
}

type Query struct {
}
