// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewProfile struct {
	ID        string  `json:"id"`
	UserID    string  `json:"userId"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
	NickName  *string `json:"nickName,omitempty"`
	Bio       *string `json:"bio,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type NewUser struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Query struct {
}
